# Generated by Django 4.0.4 on 2022-04-17 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='signup',
            table='signup',
        ),
    ]
