# Generated by Django 4.0.4 on 2022-04-18 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0003_alter_signup_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='emailid',
            field=models.EmailField(max_length=200, null=True),
        ),
    ]
